# Generated by Django 4.0.4 on 2022-05-13 00:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('img_src', models.CharField(max_length=150)),
                ('developer', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('release', models.DateTimeField(verbose_name='Release Date')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LevelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='Prefer not', max_length=50)),
                ('birthday', models.CharField(max_length=50)),
                ('img_src', models.CharField(max_length=150)),
                ('location', models.CharField(default='Earth', max_length=50)),
                ('joined', models.DateTimeField(verbose_name='Joined')),
                ('bio', models.CharField(default='Your Bio!', max_length=500)),
                ('favorite_genres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levelcheck.genre')),
                ('leveluser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('playing', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('on_hold', models.IntegerField(default=0)),
                ('dropped', models.IntegerField(default=0)),
                ('plan_to_play', models.IntegerField(default=0)),
                ('characters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='levelcheck.character')),
                ('games', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='levelcheck.game')),
                ('leveluser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='levelcheck.leveluser')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('comment', models.CharField(max_length=500)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='levelcheck.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelcheck.genre'),
        ),
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelcheck.game'),
        ),
    ]
