# Generated by Django 4.0.4 on 2022-05-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelcheck', '0003_remove_game_img_src_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(upload_to='games/'),
        ),
    ]
