# Generated by Django 4.0.3 on 2022-05-14 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('levelcheck', '0004_alter_game_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='leveluser',
            name='favorite_genres',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AddField(
            model_name='character',
            name='pub_date',
            field=models.DateTimeField(default='2000-01-01', verbose_name='Posted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default='2000-01-01', verbose_name='Posted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='genres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levelcheck.genre'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levelcheck.review'),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='Posted')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelcheck.comment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
