# Generated by Django 4.0.3 on 2022-05-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelcheck', '0005_comment_remove_leveluser_favorite_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release',
            field=models.DateField(verbose_name='Release Date'),
        ),
    ]
