# Generated by Django 4.0.3 on 2022-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelcheck', '0006_alter_game_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='img',
            field=models.ImageField(default='default', upload_to='characters/'),
            preserve_default=False,
        ),
    ]
