# Generated by Django 4.0.3 on 2022-05-14 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('levelcheck', '0009_alter_character_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted'),
        ),
    ]
