# Generated by Django 4.0.3 on 2022-05-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelcheck', '0010_alter_character_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(default='hello', max_length=300),
            preserve_default=False,
        ),
    ]
