# Generated by Django 4.0.3 on 2022-05-15 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('levelcheck', '0016_alter_reviewfeedback_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Playing'), ('C', 'Completed'), ('H', 'Hold'), ('D', 'Dropped'), ('F', 'Plan-to-Play')], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelcheck.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
        migrations.AddConstraint(
            model_name='usergames',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='user_game_stats'),
        ),
    ]
