# Generated by Django 4.0.3 on 2022-05-15 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('levelcheck', '0017_usergames_delete_userstats_usergames_user_game_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCharacters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelcheck.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usercharacters',
            constraint=models.UniqueConstraint(fields=('user', 'character'), name='user_character_favourites'),
        ),
    ]
