# Generated by Django 4.0.3 on 2022-05-15 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelcheck', '0018_usercharacters_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercharacters',
            name='user_character_favourites',
        ),
        migrations.AddField(
            model_name='usercharacters',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='levelcheck.game'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='usercharacters',
            constraint=models.UniqueConstraint(fields=('user', 'character', 'game'), name='user_character_favourites'),
        ),
    ]
