# Generated by Django 4.0.3 on 2022-05-15 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('levelcheck', '0020_usercharacters_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='news/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted')),
            ],
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
