# Generated by Django 4.0.4 on 2022-05-11 19:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('genero', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('img_src', models.CharField(max_length=150)),
                ('dev', models.CharField(max_length=50)),
                ('pub', models.CharField(max_length=50)),
                ('release', models.DateTimeField(verbose_name='Release Date')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('img_src', models.CharField(max_length=150)),
                ('generos_pref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.generos')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('comment', models.CharField(max_length=500)),
                ('jogo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.jogo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='GeneroJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.generos')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='JogosUtilizador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.utilizador')),
                ('jogos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.jogo')),
            ],
        ),
    ]
