# Generated by Django 4.0.4 on 2022-05-11 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='release',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='release date'),
            preserve_default=False,
        ),
    ]
